### ISSUE TITLE
how to name a 'non-latin' site in readme.md?

### ISSUE THREAD

**Issue by sayo-melu** [sayo-melu/nothingblock#19]
for example, 微博 (weibo) should be in which format?

1. 微博
2. weibo
3. 微博 weibo
4. 微博 (weibo)
5. weibo 微博
6. weibo (微博)

**Comment by Logic530** [comment]
# 3

**Comment by sayo-melu** [comment]
i support 6 'weibo (微博)', because we can sort the list using the first character. and if the non-latin site have some latin character, we can separate it with a '( )'

**Comment by sayo-melu** [comment]
> 3

what about your reason?

**Comment by Logic530** [comment]
First to emphasize it is a non-latin site the non-latin part should go first.
Second () dose not look good when some item have them while others don't.
Third non-latin at start will actually keep non-latin items together after sorting which I think is better
~~And last, I didn't think that much when I chose 3~~

**Comment by sayo-melu** [comment]
> First to emphasize it is a non-latin site the non-latin part should go first.
> Second () dose not look good when some item have them while others don't.
> Third non-latin at start will actually keep non-latin items together after sorting which I think is better
> ~And last, I didn't think that much when I chose 3~

i think we should sort the non-latin site as what they are sorted in `filter-item` folder, which can make it easier to find and add item to `readme.md`.

**Comment by sayo-melu** [comment]
furthermore, i can not understand what do the 'Second () dose not look good when some item have them while others don't.' mead. can you tell the reason?

**Comment by Logic530** [comment]
just my personal feeling
~~you r admin, do what you want~~

**Comment by sayo-melu** [comment]
fix this issue at 5c2433304c4a299a0253f2ed9d4c77bcb2b5f2e1
